listening-port=3478
listening-ip=0.0.0.0
fingerprint
lt-cred-mech
realm=ftn.local
user=${FTN_TURN_USERNAME}:${FTN_TURN_PASSWORD}
no-cli
no-multicast-peers
no-loopback-peers
min-port=49152
max-port=49252
simple-log
