package main

import("context";"errors";"math";"net/netip";"strings";"time")
type CoreRouterNode struct{ID string `json:"id"`;Role string `json:"role"`;Address string `json:"address,omitempty"`;Protocol string `json:"protocol"`;Enabled bool `json:"enabled"`}
type CoreRouterPeer struct{ID string `json:"id"`;LocalNode string `json:"local_node"`;RemoteASN uint32 `json:"remote_asn"`;RemoteIP string `json:"remote_ip"`;AddressFamily string `json:"address_family"`;Enabled bool `json:"enabled"`}
type CoreRouterAdapter interface{Protocol()string;Capabilities(context.Context,CoreRouterNode)([]string,error);Health(context.Context,CoreRouterNode)(CoreRouterHealth,error);Peers(context.Context,CoreRouterNode)([]CoreRouterPeerState,error);PlanRouteChange(context.Context,CoreRouterNode,RouteChangeIntent)(RouteChangePlan,error)}
type CoreRouterHealth struct{NodeID string `json:"node_id"`;Healthy bool `json:"healthy"`;CheckedAt time.Time `json:"checked_at"`;LatencyMS float64 `json:"latency_ms"`;Reason string `json:"reason"`}
type CoreRouterPeerState struct{PeerID string `json:"peer_id"`;Established bool `json:"established"`;Prefixes uint64 `json:"prefixes"`;AddressFamily string `json:"address_family"`}
type RouteChangeIntent struct{Action string `json:"action"`;Prefix string `json:"prefix"`;NextHop string `json:"next_hop,omitempty"`;PeerID string `json:"peer_id,omitempty"`;ApprovalID string `json:"approval_id,omitempty"`;ChangeID string `json:"change_id,omitempty"`}
type RouteChangePlan struct{Allowed bool `json:"allowed"`;RequiresApproval bool `json:"requires_approval"`;PreChangeSnapshot bool `json:"pre_change_snapshot"`;PostChangeVerify bool `json:"post_change_verify"`;RollbackWhenSafe bool `json:"rollback_when_safe"`;Risk string `json:"risk"`;ValidationErrors []string `json:"validation_errors,omitempty"`}
func ValidateCoreRouterNode(n CoreRouterNode)error{n.ID=strings.TrimSpace(n.ID);n.Role=strings.TrimSpace(n.Role);n.Protocol=strings.TrimSpace(n.Protocol);if n.ID==""||len(n.ID)>256{return errors.New("core_node_id_required")};if n.Role!="primary"&&n.Role!="standby"{return errors.New("invalid_core_node_role")};if n.Protocol==""||len(n.Protocol)>64{return errors.New("core_router_protocol_required")};if n.Address!=""{if _,err:=netip.ParseAddr(strings.TrimSpace(n.Address));err!=nil{return errors.New("invalid_core_node_address")}};return nil}
func PlanCoreRouteChange(n CoreRouterNode,i RouteChangeIntent)RouteChangePlan{p:=RouteChangePlan{RequiresApproval:true,PreChangeSnapshot:true,PostChangeVerify:true,RollbackWhenSafe:true,Risk:"medium"};if err:=ValidateCoreRouterNode(n);err!=nil{p.Allowed=false;p.ValidationErrors=[]string{err.Error()};return p};action:=strings.ToLower(strings.TrimSpace(i.Action));prefix:=strings.TrimSpace(i.Prefix);approval:=strings.TrimSpace(i.ApprovalID);if action==""||prefix==""||len(action)>64||len(prefix)>128||len(approval)>256{p.Allowed=false;p.ValidationErrors=[]string{"route_action_prefix_or_approval_invalid"};return p};if approval==""{p.Allowed=false;p.ValidationErrors=[]string{"approval_required"};return p};parsedPrefix,err:=netip.ParsePrefix(prefix);if err!=nil{p.Allowed=false;p.ValidationErrors=[]string{"invalid_route_prefix"};return p};if action=="withdraw"{p.Risk="high"};if action!="announce"&&action!="withdraw"&&action!="attribute-change"{p.Allowed=false;p.ValidationErrors=[]string{"unsupported_route_action"};return p};if action=="announce"||action=="attribute-change"{next:=strings.TrimSpace(i.NextHop);if next==""||len(next)>64{p.Allowed=false;p.ValidationErrors=[]string{"next_hop_required"};return p};hop,err:=netip.ParseAddr(next);if err!=nil||hop.Is4()!=parsedPrefix.Addr().Is4(){p.Allowed=false;p.ValidationErrors=[]string{"invalid_next_hop"};return p}};return func()RouteChangePlan{p.Allowed=true;return p}()}
func (h CoreRouterHealth)Valid(now time.Time)bool{return strings.TrimSpace(h.NodeID)!=""&&len(strings.TrimSpace(h.NodeID))<=256&&!math.IsNaN(h.LatencyMS)&&!math.IsInf(h.LatencyMS,0)&&h.LatencyMS>=0&&!h.CheckedAt.IsZero()&&(now.IsZero()||!h.CheckedAt.After(now.Add(5*time.Minute)))}
