package main

import (
	"encoding/json"
	"errors"
	"net/http"
	"strings"
	"time"
)

type DNSGuardProfile struct { ID string `json:"id"`; ProfileKey string `json:"profile_key"`; Name string `json:"name"`; Mode string `json:"mode"`; Enabled bool `json:"enabled"`; SafeSearch bool `json:"safe_search"`; YouTubeRestricted bool `json:"youtube_restricted"`; BlockAds bool `json:"block_ads"`; BlockTrackers bool `json:"block_trackers"`; BlockMalware bool `json:"block_malware"`; BlockPhishing bool `json:"block_phishing"`; BlockAdult bool `json:"block_adult"`; BlockGambling bool `json:"block_gambling"`; BlockDating bool `json:"block_dating"`; BlockDistraction bool `json:"block_distraction"`; CustomAllowlist json.RawMessage `json:"custom_allowlist"`; CustomBlocklist json.RawMessage `json:"custom_blocklist"` }
type DNSGuardBinding struct { ID string `json:"id"`; ProfileID string `json:"profile_id"`; SubjectType string `json:"subject_type"`; SubjectRef string `json:"subject_ref"`; Enabled bool `json:"enabled"` }
type DNSGuardRequest struct { Action string `json:"action"`; ProfileID string `json:"profile_id,omitempty"`; Binding *DNSGuardBindingInput `json:"binding,omitempty"`; Profile *DNSGuardProfileInput `json:"profile,omitempty"` }
type DNSGuardBindingInput struct { ProfileID string `json:"profile_id"`; SubjectType string `json:"subject_type"`; SubjectRef string `json:"subject_ref"`; Enabled *bool `json:"enabled,omitempty"` }
type DNSGuardProfileInput struct { ProfileKey string `json:"profile_key"`; Name string `json:"name"`; Mode string `json:"mode"`; Enabled *bool `json:"enabled,omitempty"`; SafeSearch bool `json:"safe_search"`; YouTubeRestricted bool `json:"youtube_restricted"`; BlockAds bool `json:"block_ads"`; BlockTrackers bool `json:"block_trackers"`; BlockMalware bool `json:"block_malware"`; BlockPhishing bool `json:"block_phishing"`; BlockAdult bool `json:"block_adult"`; BlockGambling bool `json:"block_gambling"`; BlockDating bool `json:"block_dating"`; BlockDistraction bool `json:"block_distraction"`; CustomAllowlist []string `json:"custom_allowlist,omitempty"`; CustomBlocklist []string `json:"custom_blocklist,omitempty"` }

var errDNSGuardApprovalResolved = errors.New("approval_already_resolved")

func (a *App) dnsGuardProfiles(w http.ResponseWriter, r *http.Request) { if !method(w,r,http.MethodGet)||!requirePermission(a,"dns.filter.read",w,r){return};if a.db==nil{jsonResponse(w,503,map[string]string{"error":"database_unavailable"});return};rc:=requestInfo(r);rows,err:=a.db.Query(r.Context(),`SELECT id::text, profile_key, name, mode, enabled, safe_search, youtube_restricted, block_ads, block_trackers, block_malware, block_phishing, block_adult, block_gambling, block_dating, block_distraction, custom_allowlist, custom_blocklist FROM dns_filter_profiles WHERE tenant_id=$1::uuid ORDER BY profile_key`,rc.TenantID);if err!=nil{jsonResponse(w,500,map[string]string{"error":"dns_profiles_query_failed"});return};defer rows.Close();out:=make([]DNSGuardProfile,0);for rows.Next(){var p DNSGuardProfile;if err:=rows.Scan(&p.ID,&p.ProfileKey,&p.Name,&p.Mode,&p.Enabled,&p.SafeSearch,&p.YouTubeRestricted,&p.BlockAds,&p.BlockTrackers,&p.BlockMalware,&p.BlockPhishing,&p.BlockAdult,&p.BlockGambling,&p.BlockDating,&p.BlockDistraction,&p.CustomAllowlist,&p.CustomBlocklist);err!=nil{jsonResponse(w,500,map[string]string{"error":"dns_profiles_decode_failed"});return};out=append(out,p)};if err:=rows.Err();err!=nil{jsonResponse(w,500,map[string]string{"error":"dns_profiles_query_failed"});return};jsonResponse(w,200,map[string]any{"profiles":out}) }
func (a *App) dnsGuardBindings(w http.ResponseWriter, r *http.Request) { if !method(w,r,http.MethodGet)||!requirePermission(a,"dns.filter.read",w,r){return};if a.db==nil{jsonResponse(w,503,map[string]string{"error":"database_unavailable"});return};rc:=requestInfo(r);rows,err:=a.db.Query(r.Context(),`SELECT id::text, profile_id::text, subject_type, subject_ref, enabled FROM dns_filter_bindings WHERE tenant_id=$1::uuid ORDER BY subject_type,subject_ref`,rc.TenantID);if err!=nil{jsonResponse(w,500,map[string]string{"error":"dns_bindings_query_failed"});return};defer rows.Close();out:=make([]DNSGuardBinding,0);for rows.Next(){var b DNSGuardBinding;if err:=rows.Scan(&b.ID,&b.ProfileID,&b.SubjectType,&b.SubjectRef,&b.Enabled);err!=nil{jsonResponse(w,500,map[string]string{"error":"dns_bindings_decode_failed"});return};out=append(out,b)};if err:=rows.Err();err!=nil{jsonResponse(w,500,map[string]string{"error":"dns_bindings_query_failed"});return};jsonResponse(w,200,map[string]any{"bindings":out}) }
func (a *App) dnsGuardEvents(w http.ResponseWriter, r *http.Request) { if !method(w,r,http.MethodGet)||!requirePermission(a,"dns.filter.read",w,r){return};if a.db==nil{jsonResponse(w,503,map[string]string{"error":"database_unavailable"});return};rc:=requestInfo(r);rows,err:=a.db.Query(r.Context(),`SELECT id::text,COALESCE(profile_id::text,''),subject_ref,domain_hash,category,decision,reason,created_at FROM dns_filter_events WHERE tenant_id=$1::uuid ORDER BY created_at DESC LIMIT 100`,rc.TenantID);if err!=nil{jsonResponse(w,500,map[string]string{"error":"dns_events_query_failed"});return};defer rows.Close();type event struct{ID,ProfileID,SubjectRef,DomainHash,Category,Decision,Reason string;CreatedAt any};out:=make([]event,0);for rows.Next(){var e event;if err:=rows.Scan(&e.ID,&e.ProfileID,&e.SubjectRef,&e.DomainHash,&e.Category,&e.Decision,&e.Reason,&e.CreatedAt);err!=nil{jsonResponse(w,500,map[string]string{"error":"dns_events_decode_failed"});return};out=append(out,e)};if err:=rows.Err();err!=nil{jsonResponse(w,500,map[string]string{"error":"dns_events_query_failed"});return};jsonResponse(w,200,map[string]any{"events":out}) }
func (a *App) dnsGuardSummary(w http.ResponseWriter,r *http.Request){if !method(w,r,http.MethodGet)||!requirePermission(a,"dns.filter.read",w,r){return};if a.db==nil{jsonResponse(w,503,map[string]string{"error":"database_unavailable"});return};rc:=requestInfo(r);var profiles,bindings,events int;if err:=a.db.QueryRow(r.Context(),`SELECT count(*) FROM dns_filter_profiles WHERE tenant_id=$1::uuid`,rc.TenantID).Scan(&profiles);err!=nil{jsonResponse(w,500,map[string]string{"error":"dns_profiles_count_failed"});return};if err:=a.db.QueryRow(r.Context(),`SELECT count(*) FROM dns_filter_bindings WHERE tenant_id=$1::uuid AND enabled=true`,rc.TenantID).Scan(&bindings);err!=nil{jsonResponse(w,500,map[string]string{"error":"dns_bindings_count_failed"});return};if err:=a.db.QueryRow(r.Context(),`SELECT count(*) FROM dns_filter_events WHERE tenant_id=$1::uuid AND created_at>=now()-interval '24 hours'`,rc.TenantID).Scan(&events);err!=nil{jsonResponse(w,500,map[string]string{"error":"dns_events_count_failed"});return};jsonResponse(w,200,map[string]any{"profiles":profiles,"active_bindings":bindings,"events_24h":events,"enforcement_dataplane":"policy-compiler-ready"})}
func (a *App) dnsGuardRequest(w http.ResponseWriter,r *http.Request){if !method(w,r,http.MethodPost)||!requirePermission(a,"dns.filter.change",w,r){return};if a.db==nil{jsonResponse(w,503,map[string]string{"error":"database_unavailable"});return};var req DNSGuardRequest;if err:=json.NewDecoder(r.Body).Decode(&req);err!=nil{jsonResponse(w,400,map[string]string{"error":"invalid_json"});return};req.Action=strings.TrimSpace(req.Action);if req.Action!="profile.upsert"&&req.Action!="profile.disable"&&req.Action!="binding.upsert"&&req.Action!="binding.disable"{jsonResponse(w,400,map[string]string{"error":"invalid_action"});return};if (req.Action=="profile.upsert"&&req.Profile==nil)||(req.Action=="binding.upsert"&&req.Binding==nil){jsonResponse(w,400,map[string]string{"error":"payload_required"});return};if req.Profile!=nil{if req.Profile.Mode!="basic"&&req.Profile.Mode!="family"&&req.Profile.Mode!="strict"&&req.Profile.Mode!="custom"{jsonResponse(w,400,map[string]string{"error":"invalid_profile_mode"});return};if strings.TrimSpace(req.Profile.ProfileKey)==""||strings.TrimSpace(req.Profile.Name)==""{jsonResponse(w,400,map[string]string{"error":"profile_identity_required"});return}};rc:=requestInfo(r);if req.Binding!=nil{if req.Binding.SubjectType!="tenant"&&req.Binding.SubjectType!="customer"&&req.Binding.SubjectType!="device"&&req.Binding.SubjectType!="network"&&req.Binding.SubjectType!="vlan"&&req.Binding.SubjectType!="pppoe"{jsonResponse(w,400,map[string]string{"error":"invalid_subject_type"});return};if strings.TrimSpace(req.Binding.SubjectRef)==""||strings.TrimSpace(req.Binding.ProfileID)==""{jsonResponse(w,400,map[string]string{"error":"binding_fields_required"});return};var ok bool;if err:=a.db.QueryRow(r.Context(),`SELECT EXISTS(SELECT 1 FROM dns_filter_profiles WHERE id=$1::uuid AND tenant_id=$2::uuid)`,req.Binding.ProfileID,rc.TenantID).Scan(&ok);err!=nil||!ok{jsonResponse(w,404,map[string]string{"error":"profile_not_found"});return}}
payload:=map[string]any{"action":req.Action,"profile":req.Profile,"binding":req.Binding};hash:=requestScopedHash(r,payload);var approvalID,status string;var expires time.Time;err:=a.db.QueryRow(r.Context(),`INSERT INTO change_approvals(tenant_id,requested_by,action,resource,request_hash,status,expires_at) VALUES($1,$2,$3,$4,$5,'pending',now()+interval '1 hour') ON CONFLICT(tenant_id,request_hash) DO UPDATE SET requested_by=excluded.requested_by,action=excluded.action,resource=excluded.resource,status='pending',expires_at=excluded.expires_at,approved_by=null,executed_at=null,updated_at=now() WHERE change_approvals.status='pending' AND change_approvals.expires_at<=now() RETURNING id::text,status,expires_at`,rc.TenantID,rc.PrincipalID,"dns.filter."+req.Action,"dns-guard/policy",hash).Scan(&approvalID,&status,&expires);if err!=nil {var existingID,existingStatus string;var existingExpires time.Time;lookupErr:=a.db.QueryRow(r.Context(),`SELECT id::text,status,expires_at FROM change_approvals WHERE tenant_id=$1::uuid AND request_hash=$2`,rc.TenantID,hash).Scan(&existingID,&existingStatus,&existingExpires);if lookupErr==nil {if existingStatus!="pending"||!existingExpires.After(time.Now().UTC()){jsonResponse(w,409,map[string]string{"error":errDNSGuardApprovalResolved.Error()});return};a.audit(r,"dns.filter.request",existingID,"pending",map[string]any{"action":req.Action,"request_hash":hash,"approval_status":existingStatus});jsonResponse(w,202,map[string]any{"status":"pending","approval_required":true,"approval_id":existingID,"request_hash":hash});return};jsonResponse(w,500,map[string]string{"error":"approval_persist_failed"});return};a.audit(r,"dns.filter.request",approvalID,"pending",map[string]any{"action":req.Action,"request_hash":hash});jsonResponse(w,202,map[string]any{"status":"pending","approval_required":true,"approval_id":approvalID,"request_hash":hash})}
func mustJSON(v any) []byte { b,_:=json.Marshal(v);return b }
type DNSGuardDecision struct {Decision string `json:"decision"`;Category string `json:"category"`;Reason string `json:"reason"`}
func CompileDNSGuardDecision(p DNSGuardProfile, category, domain string) DNSGuardDecision {d:=strings.ToLower(strings.TrimSuffix(strings.TrimSpace(domain),"."));cat:=strings.ToLower(strings.TrimSpace(category));if listContains(p.CustomAllowlist,d){return DNSGuardDecision{"allow",cat,"custom_allowlist"}};if listContains(p.CustomBlocklist,d){return DNSGuardDecision{"block",cat,"custom_blocklist"}};blocked:=map[string]bool{"ads":p.BlockAds,"trackers":p.BlockTrackers,"malware":p.BlockMalware,"phishing":p.BlockPhishing,"adult":p.BlockAdult,"gambling":p.BlockGambling,"dating":p.BlockDating,"distraction":p.BlockDistraction};if blocked[cat]{return DNSGuardDecision{"block",cat,"category_policy"}};return DNSGuardDecision{"allow",cat,"default_allow"}}
func listContains(raw json.RawMessage, domain string) bool {var xs []string;if len(raw)==0||json.Unmarshal(raw,&xs)!=nil{return false};for _,x:=range xs{if strings.TrimSuffix(strings.ToLower(strings.TrimSpace(x)),".")==domain{return true}};return false}
