package main

import (
    "encoding/json"
    "net/http"
    "strings"
    "time"
)

type durableJob struct { ID string `json:"id"`; TenantID string `json:"tenant_id,omitempty"`; JobType string `json:"job_type"`; Payload json.RawMessage `json:"payload"`; Status string `json:"status"`; Attempts int `json:"attempts"`; MaxAttempts int `json:"max_attempts"`; AvailableAt string `json:"available_at"`; LockedBy string `json:"locked_by,omitempty"`; LastError string `json:"last_error,omitempty"`; CorrelationID string `json:"correlation_id"`; CreatedAt string `json:"created_at"`; UpdatedAt string `json:"updated_at"` }

type jobSubmit struct { TenantID string `json:"tenant_id,omitempty"`; IdempotencyKey string `json:"idempotency_key"`; JobType string `json:"job_type"`; Payload json.RawMessage `json:"payload"`; MaxAttempts int `json:"max_attempts,omitempty"`; AvailableAt *time.Time `json:"available_at,omitempty"` }

type jobClaim struct { WorkerID string `json:"worker_id"`; LeaseSeconds int `json:"lease_seconds,omitempty"` }

func (a *App) submitJob(w http.ResponseWriter,r *http.Request){
    if !method(w,r,http.MethodPost)||!requirePermission(a,"job.submit",w,r){return}; if a.db==nil{jsonResponse(w,503,map[string]string{"error":"database_required"});return}
    var in jobSubmit; if err:=json.NewDecoder(r.Body).Decode(&in);err!=nil||strings.TrimSpace(in.JobType)==""{jsonResponse(w,400,map[string]string{"error":"invalid_job"});return}
    rc:=requestInfo(r);tenant:=rc.TenantID;if tenant==""{tenant=in.TenantID};if tenant==""{jsonResponse(w,400,map[string]string{"error":"tenant_required"});return};key:=strings.TrimSpace(in.IdempotencyKey);if key==""{key=strings.TrimSpace(r.Header.Get("Idempotency-Key"))};if key==""{jsonResponse(w,400,map[string]string{"error":"idempotency_key_required"});return};if len(in.Payload)==0{in.Payload=json.RawMessage(`{}`)};if !json.Valid(in.Payload){jsonResponse(w,400,map[string]string{"error":"invalid_payload"});return};if in.MaxAttempts<=0||in.MaxAttempts>20{in.MaxAttempts=3}
    available:=time.Now().UTC();if in.AvailableAt!=nil{available=in.AvailableAt.UTC()};var j durableJob
    err:=a.db.QueryRow(r.Context(),`insert into durable_jobs(tenant_id,idempotency_key,job_type,payload,max_attempts,available_at,correlation_id) values($1::uuid,$2,$3,$4::jsonb,$5,$6,$7) on conflict(idempotency_key) do update set updated_at=durable_jobs.updated_at returning id::text,tenant_id::text,job_type,payload::text,status,attempts,max_attempts,available_at::text,coalesce(locked_by,''),last_error,correlation_id,created_at::text,updated_at::text`,tenant,key,in.JobType,string(in.Payload),in.MaxAttempts,available,rc.CorrelationID).Scan(&j.ID,&j.TenantID,&j.JobType,&j.Payload,&j.Status,&j.Attempts,&j.MaxAttempts,&j.AvailableAt,&j.LockedBy,&j.LastError,&j.CorrelationID,&j.CreatedAt,&j.UpdatedAt)
    if err!=nil{jsonResponse(w,500,map[string]string{"error":"job_submit_failed"});return};a.audit(r,"job.submit",j.ID,"accepted",j);jsonResponse(w,202,j)
}

func (a *App) getJob(w http.ResponseWriter,r *http.Request){if !method(w,r,http.MethodGet)||!requirePermission(a,"job.read",w,r){return};if a.db==nil{jsonResponse(w,503,map[string]string{"error":"database_required"});return};id:=strings.TrimPrefix(r.URL.Path,"/api/v1/jobs/");if id==""{jsonResponse(w,400,map[string]string{"error":"job_id_required"});return};var j durableJob;err:=a.db.QueryRow(r.Context(),`select id::text,coalesce(tenant_id::text,''),job_type,payload::text,status,attempts,max_attempts,available_at::text,coalesce(locked_by,''),last_error,correlation_id,created_at::text,updated_at::text from durable_jobs where id=$1::uuid and (tenant_id=$2::uuid)`,id,requestInfo(r).TenantID).Scan(&j.ID,&j.TenantID,&j.JobType,&j.Payload,&j.Status,&j.Attempts,&j.MaxAttempts,&j.AvailableAt,&j.LockedBy,&j.LastError,&j.CorrelationID,&j.CreatedAt,&j.UpdatedAt);if err!=nil{jsonResponse(w,404,map[string]string{"error":"job_not_found"});return};jsonResponse(w,200,j)}

func (a *App) claimJob(w http.ResponseWriter,r *http.Request){if !method(w,r,http.MethodPost)||!requirePermission(a,"job.execute",w,r){return};if a.db==nil{jsonResponse(w,503,map[string]string{"error":"database_required"});return};var in jobClaim;if err:=json.NewDecoder(r.Body).Decode(&in);err!=nil||strings.TrimSpace(in.WorkerID)==""{jsonResponse(w,400,map[string]string{"error":"worker_id_required"});return};lease:=in.LeaseSeconds;if lease<10||lease>3600{lease=60};rc:=requestInfo(r);tx,err:=a.db.Begin(r.Context());if err!=nil{jsonResponse(w,500,map[string]string{"error":"claim_begin_failed"});return};defer tx.Rollback(r.Context())
    var j durableJob;err=tx.QueryRow(r.Context(),`with candidate as (select id from durable_jobs where tenant_id=$1::uuid and status='queued' and available_at<=now() and attempts<max_attempts order by available_at,created_at for update skip locked limit 1) update durable_jobs d set status='running',attempts=d.attempts+1,locked_at=now(),locked_by=$2,started_at=coalesce(d.started_at,now()),updated_at=now() from candidate c where d.id=c.id returning d.id::text,d.tenant_id::text,d.job_type,d.payload::text,d.status,d.attempts,d.max_attempts,d.available_at::text,coalesce(d.locked_by,''),d.last_error,d.correlation_id,d.created_at::text,d.updated_at::text`,rc.TenantID,in.WorkerID).Scan(&j.ID,&j.TenantID,&j.JobType,&j.Payload,&j.Status,&j.Attempts,&j.MaxAttempts,&j.AvailableAt,&j.LockedBy,&j.LastError,&j.CorrelationID,&j.CreatedAt,&j.UpdatedAt)
    if err!=nil{jsonResponse(w,204,nil);return};_,err=tx.Exec(r.Context(),`insert into execution_attempts(job_id,attempt_no,worker_id,status) values($1::uuid,$2,$3,'running') on conflict(job_id,attempt_no) do nothing`,j.ID,j.Attempts,in.WorkerID);if err!=nil{jsonResponse(w,500,map[string]string{"error":"attempt_create_failed"});return};if err=tx.Commit(r.Context());err!=nil{jsonResponse(w,500,map[string]string{"error":"claim_commit_failed"});return};a.audit(r,"job.claim",j.ID,"accepted",map[string]any{"worker_id":in.WorkerID,"lease_seconds":lease,"attempt":j.Attempts});jsonResponse(w,200,j)}

func (a *App) finishJob(w http.ResponseWriter,r *http.Request){if !method(w,r,http.MethodPost)||!requirePermission(a,"job.execute",w,r){return};if a.db==nil{jsonResponse(w,503,map[string]string{"error":"database_required"});return};id:=strings.TrimPrefix(r.URL.Path,"/api/v1/jobs/");id=strings.TrimSuffix(id,"/finish");var in struct{WorkerID string `json:"worker_id"`;Success bool `json:"success"`;Error string `json:"error,omitempty"`};if err:=json.NewDecoder(r.Body).Decode(&in);err!=nil||in.WorkerID==""{jsonResponse(w,400,map[string]string{"error":"invalid_finish"});return};rc:=requestInfo(r);tx,err:=a.db.Begin(r.Context());if err!=nil{jsonResponse(w,500,map[string]string{"error":"finish_begin_failed"});return};defer tx.Rollback(r.Context());var attempts int;var maxAttempts int;var status string;err=tx.QueryRow(r.Context(),`select attempts,max_attempts,status from durable_jobs where id=$1::uuid and tenant_id=$2::uuid and locked_by=$3`,id,rc.TenantID,in.WorkerID).Scan(&attempts,&maxAttempts,&status);if err!=nil{jsonResponse(w,404,map[string]string{"error":"job_not_found"});return};if status!="running"{jsonResponse(w,409,map[string]string{"error":"job_not_running"});return};final:="failed";if in.Success{final="succeeded"};if !in.Success&&attempts<maxAttempts{final="queued"};_,err=tx.Exec(r.Context(),`update durable_jobs set status=$2,last_error=$3,locked_at=null,locked_by=null,finished_at=case when $2='succeeded' or $2='failed' then now() else null end,available_at=case when $2='queued' then now()+make_interval(secs => least(3600,greatest(1,(2 ^ least(10,attempts))::int))) else available_at end,updated_at=now() where id=$1::uuid`,id,final,in.Error);if err!=nil{jsonResponse(w,500,map[string]string{"error":"job_finish_failed"});return};attemptStatus:="failed";if in.Success{attemptStatus="succeeded"};_,err=tx.Exec(r.Context(),`update execution_attempts set status=$2,error=$3,finished_at=now() where job_id=$1::uuid and attempt_no=$4`,id,attemptStatus,in.Error,attempts);if err!=nil{jsonResponse(w,500,map[string]string{"error":"attempt_finish_failed"});return};if err=tx.Commit(r.Context());err!=nil{jsonResponse(w,500,map[string]string{"error":"finish_commit_failed"});return};a.audit(r,"job.finish",id,final,map[string]any{"worker_id":in.WorkerID,"attempt":attempts,"error":in.Error});jsonResponse(w,202,map[string]string{"id":id,"status":final})}
