package main

import (
    "crypto/sha256"
    "encoding/hex"
    "encoding/json"
    "errors"
    "net/http"
    "strings"
    "time"

    "github.com/jackc/pgx/v5"
)

type durableJob struct { ID string `json:"id"`; TenantID string `json:"tenant_id,omitempty"`; JobType string `json:"job_type"`; Payload json.RawMessage `json:"payload"`; Status string `json:"status"`; Attempts int `json:"attempts"`; MaxAttempts int `json:"max_attempts"`; AvailableAt string `json:"available_at"`; LockedBy string `json:"locked_by,omitempty"`; LastError string `json:"last_error,omitempty"`; CorrelationID string `json:"correlation_id"`; CreatedAt string `json:"created_at"`; UpdatedAt string `json:"updated_at"`; ApprovalID string `json:"approval_id,omitempty"`; ExecutionAction string `json:"execution_action,omitempty"` }
type jobSubmit struct { TenantID string `json:"tenant_id,omitempty"`; IdempotencyKey string `json:"idempotency_key"`; JobType string `json:"job_type"`; Payload json.RawMessage `json:"payload"`; MaxAttempts int `json:"max_attempts,omitempty"`; AvailableAt *time.Time `json:"available_at,omitempty"`; ApprovalID string `json:"approval_id,omitempty"`; ExecutionAction string `json:"execution_action,omitempty"`; RollbackPayload json.RawMessage `json:"rollback_payload,omitempty"` }
type jobClaim struct { WorkerID string `json:"worker_id"`; LeaseSeconds int `json:"lease_seconds,omitempty"` }

func privilegedJobType(jobType, action string) bool { if action=="" { return false }; for _, p := range []string{"network.","router.","dns.","security.","config."} { if strings.HasPrefix(jobType,p) { return true } }; return false }
func jobRequestHash(in jobSubmit) string { h:=sha256.New(); _,_=h.Write([]byte(in.JobType)); _,_=h.Write([]byte{0}); _,_=h.Write(in.Payload); _,_=h.Write([]byte{0}); _,_=h.Write([]byte(in.ExecutionAction)); _,_=h.Write([]byte{0}); _,_=h.Write([]byte(in.ApprovalID)); _,_=h.Write([]byte{0}); _,_=h.Write(in.RollbackPayload); return hex.EncodeToString(h.Sum(nil)) }

func (a *App) submitJob(w http.ResponseWriter,r *http.Request){
    if !method(w,r,http.MethodPost)||!requirePermission(a,"job.submit",w,r){return};if a.db==nil{jsonResponse(w,503,map[string]string{"error":"database_required"});return}
    var in jobSubmit;if err:=json.NewDecoder(r.Body).Decode(&in);err!=nil||strings.TrimSpace(in.JobType)==""{jsonResponse(w,400,map[string]string{"error":"invalid_job"});return};rc:=requestInfo(r);tenant:=rc.TenantID;if tenant==""{tenant=in.TenantID};if tenant==""{jsonResponse(w,400,map[string]string{"error":"tenant_required"});return};key:=strings.TrimSpace(in.IdempotencyKey);if key==""{key=strings.TrimSpace(r.Header.Get("Idempotency-Key"))};if key==""{jsonResponse(w,400,map[string]string{"error":"idempotency_key_required"});return};if len(in.Payload)==0{in.Payload=json.RawMessage(`{}`)};if !json.Valid(in.Payload){jsonResponse(w,400,map[string]string{"error":"invalid_payload"});return};if in.MaxAttempts<=0||in.MaxAttempts>20{in.MaxAttempts=3};if in.ExecutionAction==""{in.ExecutionAction=in.JobType};if len(in.RollbackPayload)==0{in.RollbackPayload=json.RawMessage(`{}`)};privileged:=privilegedJobType(in.JobType,in.ExecutionAction);if privileged&&strings.TrimSpace(in.ApprovalID)==""{jsonResponse(w,409,map[string]string{"error":"approval_required"});return};if in.ApprovalID!=""{var status string;err:=a.db.QueryRow(r.Context(),`select status from change_approvals where id=$1::uuid and tenant_id=$2::uuid and (expires_at is null or expires_at>now())`,in.ApprovalID,tenant).Scan(&status);if errors.Is(err,pgx.ErrNoRows){jsonResponse(w,409,map[string]string{"error":"approval_not_found_or_expired"});return};if err!=nil||status!="approved"{jsonResponse(w,409,map[string]string{"error":"approval_not_approved"});return}}
    available:=time.Now().UTC();if in.AvailableAt!=nil{available=in.AvailableAt.UTC()};hash:=jobRequestHash(in);var j durableJob;var existingHash string
    err:=a.db.QueryRow(r.Context(),`insert into durable_jobs(tenant_id,idempotency_key,job_type,payload,max_attempts,available_at,execution_action,approval_id,rollback_payload,correlation_id,request_hash) values($1::uuid,$2,$3,$4::jsonb,$5,$6,$7,nullif($8,'')::uuid,$9::jsonb,$10,$11) on conflict(idempotency_key) do update set updated_at=durable_jobs.updated_at returning id::text,tenant_id::text,job_type,payload::text,status,attempts,max_attempts,available_at::text,coalesce(locked_by,''),last_error,correlation_id,created_at::text,updated_at::text,coalesce(approval_id::text,''),execution_action,request_hash`,tenant,key,in.JobType,string(in.Payload),in.MaxAttempts,available,in.ExecutionAction,in.ApprovalID,string(in.RollbackPayload),rc.CorrelationID,hash).Scan(&j.ID,&j.TenantID,&j.JobType,&j.Payload,&j.Status,&j.Attempts,&j.MaxAttempts,&j.AvailableAt,&j.LockedBy,&j.LastError,&j.CorrelationID,&j.CreatedAt,&j.UpdatedAt,&j.ApprovalID,&j.ExecutionAction,&existingHash);if err!=nil{jsonResponse(w,500,map[string]string{"error":"job_submit_failed"});return};if existingHash!=""&&existingHash!=hash{jsonResponse(w,409,map[string]string{"error":"idempotency_conflict"});return};a.audit(r,"job.submit",j.ID,"accepted",j);jsonResponse(w,202,j)
}

func (a *App) getJob(w http.ResponseWriter,r *http.Request){if !method(w,r,http.MethodGet)||!requirePermission(a,"job.read",w,r){return};if a.db==nil{jsonResponse(w,503,map[string]string{"error":"database_required"});return};id:=strings.TrimPrefix(r.URL.Path,"/api/v1/jobs/");for _,s:=range []string{"/finish","/cancel","/verify","/rollback"}{id=strings.TrimSuffix(id,s)};if id==""{jsonResponse(w,400,map[string]string{"error":"job_id_required"});return};var j durableJob;err:=a.db.QueryRow(r.Context(),`select id::text,coalesce(tenant_id::text,''),job_type,payload::text,status,attempts,max_attempts,available_at::text,coalesce(locked_by,''),last_error,correlation_id,created_at::text,updated_at::text,coalesce(approval_id::text,''),execution_action from durable_jobs where id=$1::uuid and tenant_id=$2::uuid`,id,requestInfo(r).TenantID).Scan(&j.ID,&j.TenantID,&j.JobType,&j.Payload,&j.Status,&j.Attempts,&j.MaxAttempts,&j.AvailableAt,&j.LockedBy,&j.LastError,&j.CorrelationID,&j.CreatedAt,&j.UpdatedAt,&j.ApprovalID,&j.ExecutionAction);if err!=nil{jsonResponse(w,404,map[string]string{"error":"job_not_found"});return};jsonResponse(w,200,j)}

func (a *App) claimJob(w http.ResponseWriter,r *http.Request){if !method(w,r,http.MethodPost)||!requirePermission(a,"job.execute",w,r){return};if a.db==nil{jsonResponse(w,503,map[string]string{"error":"database_required"});return};var in jobClaim;if err:=json.NewDecoder(r.Body).Decode(&in);err!=nil||strings.TrimSpace(in.WorkerID)==""{jsonResponse(w,400,map[string]string{"error":"worker_id_required"});return};lease:=in.LeaseSeconds;if lease<10||lease>3600{lease=300};rc:=requestInfo(r);tx,err:=a.db.Begin(r.Context());if err!=nil{jsonResponse(w,500,map[string]string{"error":"claim_begin_failed"});return};defer tx.Rollback(r.Context());var j durableJob;var approval *string
    err=tx.QueryRow(r.Context(),`with candidate as (select d.id from durable_jobs d left join change_approvals a on a.id=d.approval_id where d.tenant_id=$1::uuid and ((d.status='queued' and d.available_at<=now()) or (d.status='running' and d.lease_expires_at is not null and d.lease_expires_at<=now())) and d.attempts<d.max_attempts and (d.approval_id is null or (a.status='approved' and (a.expires_at is null or a.expires_at>now()))) order by d.available_at,d.created_at for update skip locked limit 1) update durable_jobs d set status='running',attempts=d.attempts+1,locked_at=now(),locked_by=$2,lease_expires_at=now()+make_interval(secs=>$3),started_at=coalesce(d.started_at,now()),updated_at=now() from candidate c where d.id=c.id returning d.id::text,d.tenant_id::text,d.job_type,d.payload::text,d.status,d.attempts,d.max_attempts,d.available_at::text,coalesce(d.locked_by,''),d.last_error,d.correlation_id,d.created_at::text,d.updated_at::text,coalesce(d.approval_id::text,''),d.execution_action`,rc.TenantID,in.WorkerID,lease).Scan(&j.ID,&j.TenantID,&j.JobType,&j.Payload,&j.Status,&j.Attempts,&j.MaxAttempts,&j.AvailableAt,&j.LockedBy,&j.LastError,&j.CorrelationID,&j.CreatedAt,&j.UpdatedAt,&approval,&j.ExecutionAction);if errors.Is(err,pgx.ErrNoRows){w.WriteHeader(http.StatusNoContent);return};if err!=nil{jsonResponse(w,500,map[string]string{"error":"job_claim_failed"});return};if approval!=nil{j.ApprovalID=*approval};_,err=tx.Exec(r.Context(),`insert into execution_attempts(job_id,attempt_no,worker_id,status) values($1::uuid,$2,$3,'running') on conflict(job_id,attempt_no) do nothing`,j.ID,j.Attempts,in.WorkerID);if err!=nil{jsonResponse(w,500,map[string]string{"error":"attempt_create_failed"});return};if err=tx.Commit(r.Context());err!=nil{jsonResponse(w,500,map[string]string{"error":"claim_commit_failed"});return};a.audit(r,"job.claim",j.ID,"running",map[string]any{"worker_id":in.WorkerID,"lease_seconds":lease,"attempt":j.Attempts,"approval_id":j.ApprovalID});jsonResponse(w,200,j)}

func (a *App) finishJob(w http.ResponseWriter,r *http.Request){if !method(w,r,http.MethodPost)||!requirePermission(a,"job.execute",w,r){return};if a.db==nil{jsonResponse(w,503,map[string]string{"error":"database_required"});return};id:=strings.TrimSuffix(strings.TrimPrefix(r.URL.Path,"/api/v1/jobs/"),"/finish");var in struct{WorkerID string `json:"worker_id"`;AttemptNo int `json:"attempt_no"`;Success bool `json:"success"`;Error string `json:"error,omitempty"`;Verification json.RawMessage `json:"verification,omitempty"`};if err:=json.NewDecoder(r.Body).Decode(&in);err!=nil||in.WorkerID==""||in.AttemptNo<=0{jsonResponse(w,400,map[string]string{"error":"invalid_finish"});return};if len(in.Verification)==0{in.Verification=json.RawMessage(`{}`)};rc:=requestInfo(r);tx,err:=a.db.Begin(r.Context());if err!=nil{jsonResponse(w,500,map[string]string{"error":"finish_begin_failed"});return};defer tx.Rollback(r.Context());var attempts,maxAttempts int;var status,lockedBy string;var approvalID *string;err=tx.QueryRow(r.Context(),`select attempts,max_attempts,status,coalesce(locked_by,''),approval_id::text from durable_jobs where id=$1::uuid and tenant_id=$2::uuid for update`,id,rc.TenantID).Scan(&attempts,&maxAttempts,&status,&lockedBy,&approvalID);if err!=nil{jsonResponse(w,404,map[string]string{"error":"job_not_found"});return};if status!="running"||lockedBy!=in.WorkerID||attempts!=in.AttemptNo{jsonResponse(w,409,map[string]string{"error":"job_lease_conflict"});return};final:="failed";if in.Success{final="succeeded"};if !in.Success&&attempts<maxAttempts{final="queued"};backoff:=attempts*attempts;if backoff<1{backoff=1};if backoff>300{backoff=300};_,err=tx.Exec(r.Context(),`update durable_jobs set status=$2,last_error=$3,locked_at=null,locked_by=null,lease_expires_at=null,finished_at=case when $2 in ('succeeded','failed') then now() else null end,available_at=case when $2='queued' then now()+make_interval(secs=>$4) else available_at end,verification_payload=$5::jsonb,updated_at=now() where id=$1::uuid`,id,final,in.Error,backoff,string(in.Verification));if err!=nil{jsonResponse(w,500,map[string]string{"error":"job_finish_failed"});return};attemptStatus:="failed";if in.Success{attemptStatus="succeeded"};_,err=tx.Exec(r.Context(),`update execution_attempts set status=$2,error=$3,finished_at=now() where job_id=$1::uuid and attempt_no=$4 and worker_id=$5`,id,attemptStatus,in.Error,in.AttemptNo,in.WorkerID);if err!=nil{jsonResponse(w,500,map[string]string{"error":"attempt_finish_failed"});return};if err=tx.Commit(r.Context());err!=nil{jsonResponse(w,500,map[string]string{"error":"finish_commit_failed"});return};a.audit(r,"job.finish",id,final,map[string]any{"worker_id":in.WorkerID,"attempt":in.AttemptNo,"approval_id":approvalID,"verification":json.RawMessage(in.Verification)});jsonResponse(w,200,map[string]any{"id":id,"status":final,"retry":final=="queued"})}

func (a *App) cancelJob(w http.ResponseWriter,r *http.Request){if !method(w,r,http.MethodPost)||!requirePermission(a,"job.submit",w,r){return};if a.db==nil{jsonResponse(w,503,map[string]string{"error":"database_required"});return};id:=strings.TrimSuffix(strings.TrimPrefix(r.URL.Path,"/api/v1/jobs/"),"/cancel");rc:=requestInfo(r);res,err:=a.db.Exec(r.Context(),`update durable_jobs set status='cancelled',locked_at=null,locked_by=null,lease_expires_at=null,finished_at=now(),updated_at=now() where id=$1::uuid and tenant_id=$2::uuid and status in ('queued','running')`,id,rc.TenantID);if err!=nil{jsonResponse(w,500,map[string]string{"error":"job_cancel_failed"});return};if res.RowsAffected()==0{jsonResponse(w,409,map[string]string{"error":"job_not_cancellable"});return};a.audit(r,"job.cancel",id,"cancelled",nil);jsonResponse(w,200,map[string]string{"job_id":id,"status":"cancelled"})}
