package controlplane

// ServerState is the normalized state reported by an FTN server agent.
type ServerState struct {
	ID         string
	Version    string
	Healthy    bool
	CPUPercent float64
	RAMPercent float64
	DiskPercent float64
	Services   []string
}

// DesiredState is the validated target state generated by the control plane.
type DesiredState struct {
	ServerID string
	Services []string
}

// AnalysisResult contains recommendations without executing them.
type AnalysisResult struct {
	ServerID string
	Healthy  bool
	Desired  DesiredState
	Reason   string
}

// Analyze converts observed server state into a bounded desired-state plan.
// It intentionally does not perform network I/O or push changes.
func Analyze(s ServerState) AnalysisResult {
	return AnalysisResult{
		ServerID: s.ID,
		Healthy:  s.Healthy,
		Desired: DesiredState{ServerID: s.ID, Services: append([]string(nil), s.Services...)},
		Reason:   "observed state normalized; deployment requires the control-plane policy gate",
	}
}
