package authenticator
import("errors";"sort";"strings";"sync";"time")
type PrincipalType string
const(PrincipalUser PrincipalType="user";PrincipalService PrincipalType="service";PrincipalAgent PrincipalType="agent")
type Principal struct{ID string;Type PrincipalType;Enabled bool;CreatedAt time.Time}
type Role struct{ID string;Capabilities []string}
type Policy struct{ID string;Effect string;Capability string;Resource string}
type IAMRegistry struct{mu sync.RWMutex;principals map[string]Principal;roles map[string]Role;assignments map[string]map[string]struct{};policies map[string]Policy}
func NewIAMRegistry()*IAMRegistry{return &IAMRegistry{principals:make(map[string]Principal),roles:make(map[string]Role),assignments:make(map[string]map[string]struct{}),policies:make(map[string]Policy)}}
func(r *IAMRegistry)UpsertPrincipal(p Principal)error{if r==nil{return errors.New("IAM registry is required")};p.ID=strings.TrimSpace(p.ID);if p.ID==""||(p.Type!=PrincipalUser&&p.Type!=PrincipalService&&p.Type!=PrincipalAgent){return errors.New("invalid principal")};if p.CreatedAt.IsZero(){p.CreatedAt=time.Now().UTC()}else{p.CreatedAt=p.CreatedAt.UTC()};r.mu.Lock();if r.principals==nil{r.principals=make(map[string]Principal)};r.principals[p.ID]=p;r.mu.Unlock();return nil}
func(r *IAMRegistry)UpsertRole(role Role)error{if r==nil{return errors.New("IAM registry is required")};role.ID=strings.TrimSpace(role.ID);if role.ID==""{return errors.New("invalid role")};caps:=make([]string,0,len(role.Capabilities));seen:=map[string]struct{}{};for _,c:=range role.Capabilities{c=strings.TrimSpace(c);if c!=""{if _,ok:=seen[c];!ok{seen[c]=struct{}{};caps=append(caps,c)}}};sort.Strings(caps);r.mu.Lock();if r.roles==nil{r.roles=make(map[string]Role)};role.Capabilities=caps;r.roles[role.ID]=role;r.mu.Unlock();return nil}
func(r *IAMRegistry)AssignRole(principalID,roleID string)error{if r==nil{return errors.New("IAM registry is required")};principalID=strings.TrimSpace(principalID);roleID=strings.TrimSpace(roleID);if principalID==""||roleID==""{return errors.New("principal and role are required")};r.mu.Lock();defer r.mu.Unlock();p,ok:=r.principals[principalID];if !ok||!p.Enabled{return errors.New("principal not found or disabled")};if _,ok:=r.roles[roleID];!ok{return errors.New("role not found")};if r.assignments[principalID]==nil{r.assignments[principalID]=make(map[string]struct{})};r.assignments[principalID][roleID]=struct{}{};return nil}
func(r *IAMRegistry)UpsertPolicy(policy Policy)error{if r==nil{return errors.New("IAM registry is required")};policy.ID=strings.TrimSpace(policy.ID);policy.Capability=strings.TrimSpace(policy.Capability);policy.Resource=strings.TrimSpace(policy.Resource);policy.Effect=strings.ToLower(strings.TrimSpace(policy.Effect));if policy.ID==""||policy.Capability==""||policy.Resource==""{return errors.New("invalid policy")};if policy.Effect!="allow"&&policy.Effect!="deny"{return errors.New("invalid policy effect")};r.mu.Lock();if r.policies==nil{r.policies=make(map[string]Policy)};r.policies[policy.ID]=policy;r.mu.Unlock();return nil}
func(r *IAMRegistry)Capabilities(principalID string)([]string,error){if r==nil{return nil,errors.New("IAM registry is required")};principalID=strings.TrimSpace(principalID);r.mu.RLock();defer r.mu.RUnlock();p,ok:=r.principals[principalID];if !ok{return nil,errors.New("principal not found")};if !p.Enabled{return nil,errors.New("principal disabled")};seen:=make(map[string]struct{});for roleID:=range r.assignments[principalID]{for _,capability:=range r.roles[roleID].Capabilities{seen[capability]=struct{}{}}};out:=make([]string,0,len(seen));for capability:=range seen{out=append(out,capability)};sort.Strings(out);return out,nil}
