package kernel

import("context";"errors";"fmt";"sort";"strings";"sync")
type ToolRequest struct{Tool string;Operation string;Target string;Parameters map[string]string};type ToolResult struct{Status string;Output string};type Tool interface{Name()string;Operations()[]string;Execute(context.Context,ToolRequest)(ToolResult,error)}
type Registry struct{mu sync.RWMutex;tools map[string]Tool}
func NewRegistry(tools ...Tool)(*Registry,error){r:=&Registry{tools:make(map[string]Tool)};for _,tool:=range tools{if tool==nil||strings.TrimSpace(tool.Name())==""{return nil,errors.New("kernel tool must have a name")};name:=strings.TrimSpace(tool.Name());if _,ok:=r.tools[name];ok{return nil,fmt.Errorf("duplicate kernel tool: %s",name)};r.tools[name]=tool};return r,nil}
func(r *Registry)Execute(ctx context.Context,request ToolRequest)(ToolResult,error){if r==nil{return ToolResult{},errors.New("kernel registry is required")};if ctx==nil{return ToolResult{},errors.New("context is required")};if err:=ctx.Err();err!=nil{return ToolResult{},err};request.Tool=strings.TrimSpace(request.Tool);request.Operation=strings.TrimSpace(request.Operation);request.Target=strings.TrimSpace(request.Target);if request.Tool==""||request.Operation==""{return ToolResult{},errors.New("tool and operation are required")};r.mu.RLock();tool,ok:=r.tools[request.Tool];r.mu.RUnlock();if !ok{return ToolResult{},fmt.Errorf("kernel tool not registered: %s",request.Tool)};allowed:=false;for _,op:=range tool.Operations(){if strings.TrimSpace(op)==request.Operation{allowed=true;break}};if !allowed{return ToolResult{},fmt.Errorf("kernel operation not allowed: %s",request.Operation)};params:=make(map[string]string,len(request.Parameters));for k,v:=range request.Parameters{k=strings.TrimSpace(k);if k!=""{params[k]=strings.TrimSpace(v)}};request.Parameters=params;return tool.Execute(ctx,request)}
func(r *Registry)DoExecute(ctx context.Context,request ToolRequest)(ToolResult,error){return r.Execute(ctx,request)}
func(r *Registry)Tools()[]string{if r==nil{return nil};r.mu.RLock();out:=make([]string,0,len(r.tools));for name:=range r.tools{out=append(out,name)};r.mu.RUnlock();sort.Strings(out);return out}
