package builder

import("errors";"strings";"sync";"time")
type Engine struct{mu sync.RWMutex;projects map[string]Project;jobs map[string]BuildJob}
func NewEngine()*Engine{return &Engine{projects:map[string]Project{},jobs:map[string]BuildJob{}}}
func(e *Engine)CreateProject(p Project)error{if e==nil{return errors.New("builder engine is required")};p.ID=strings.TrimSpace(p.ID);p.Name=strings.TrimSpace(p.Name);if p.ID==""||p.Name==""{return errors.New("project id and name are required")};if p.Target!=TargetWeb&&p.Target!=TargetAndroid&&p.Target!=TargetReact&&p.Target!=TargetFlutter{return errors.New("unsupported target")};if strings.TrimSpace(p.Backend.Language)==""||strings.TrimSpace(p.Backend.Framework)==""||strings.TrimSpace(p.Frontend.Framework)==""{return errors.New("backend and frontend specifications are required")};p.CreatedAt=time.Now().UTC();e.mu.Lock();defer e.mu.Unlock();if e.projects==nil{e.projects=map[string]Project{}};if _,exists:=e.projects[p.ID];exists{return errors.New("project already exists")};e.projects[p.ID]=p;return nil}
func(e *Engine)GetProject(id string)(Project,bool){if e==nil{return Project{},false};id=strings.TrimSpace(id);e.mu.RLock();defer e.mu.RUnlock();p,ok:=e.projects[id];return p,ok}
func(e *Engine)CreateBuild(projectID,jobID string)(BuildJob,error){if e==nil{return BuildJob{},errors.New("builder engine is required")};projectID=strings.TrimSpace(projectID);jobID=strings.TrimSpace(jobID);if projectID==""||jobID==""{return BuildJob{},errors.New("project id and job id are required")};e.mu.RLock();_,ok:=e.projects[projectID];e.mu.RUnlock();if !ok{return BuildJob{},errors.New("project not found")};job:=BuildJob{ID:jobID,ProjectID:projectID,Status:"queued"};e.mu.Lock();defer e.mu.Unlock();if e.jobs==nil{e.jobs=map[string]BuildJob{}};if _,exists:=e.jobs[jobID];exists{return BuildJob{},errors.New("build job already exists")};e.jobs[jobID]=job;return job,nil}
func(e *Engine)UpdateBuild(job BuildJob)error{if e==nil{return errors.New("builder engine is required")};job.ID=strings.TrimSpace(job.ID);if job.ID==""{return errors.New("build job id is required")};e.mu.Lock();defer e.mu.Unlock();if _,ok:=e.jobs[job.ID];!ok{return errors.New("build job not found")};e.jobs[job.ID]=job;return nil}
