package ai

import("context";"errors";"fmt";"sync";"time")
var(ErrWorkflowExists=errors.New("workflow already exists");ErrWorkflowNotFound=errors.New("workflow not found");ErrWorkflowNotRunnable=errors.New("workflow is not runnable"))
type WorkflowState string
const(WorkflowPending WorkflowState="PENDING";WorkflowRunning WorkflowState="RUNNING";WorkflowPaused WorkflowState="PAUSED";WorkflowSucceeded WorkflowState="SUCCEEDED";WorkflowFailed WorkflowState="FAILED";WorkflowCancelled WorkflowState="CANCELLED")
type WorkflowStep struct{ID string;ToolID string;Input map[string]any;Required bool}
type Workflow struct{ID string;Revision uint64;State WorkflowState;CurrentStep int;Steps []WorkflowStep;CreatedAt time.Time;UpdatedAt time.Time;LastError string}
type ToolExecutor interface{Execute(ctx context.Context,step WorkflowStep)error}
type Engine struct{mu sync.RWMutex;workflows map[string]Workflow;executor ToolExecutor}
func NewEngine(executor ToolExecutor)*Engine{return &Engine{workflows:make(map[string]Workflow),executor:executor}}
func(e *Engine)Create(w Workflow)error{if e==nil{return errors.New("workflow engine is required")};if w.ID==""||len(w.Steps)==0{return errors.New("workflow id and steps are required")};for _,s:=range w.Steps{if s.ID==""||s.ToolID==""{return errors.New("workflow steps require id and tool id")}};if w.State==""{w.State=WorkflowPending};if w.CreatedAt.IsZero(){w.CreatedAt=time.Now().UTC()};w.UpdatedAt=w.CreatedAt;e.mu.Lock();defer e.mu.Unlock();if _,ok:=e.workflows[w.ID];ok{return ErrWorkflowExists};e.workflows[w.ID]=cloneWorkflow(w);return nil}
func(e *Engine)Resume(ctx context.Context,id string)error{if e==nil{return errors.New("workflow engine is required")};if e.executor==nil{return errors.New("workflow executor is not configured")};if ctx==nil{return errors.New("context is required")};id0:=id;for{select{case<-ctx.Done():return ctx.Err();default:};e.mu.Lock();w,ok:=e.workflows[id0];if !ok{e.mu.Unlock();return ErrWorkflowNotFound};if w.State==WorkflowSucceeded||w.State==WorkflowCancelled{e.mu.Unlock();return ErrWorkflowNotRunnable};w.State=WorkflowRunning;w.UpdatedAt=time.Now().UTC();if w.CurrentStep>=len(w.Steps){w.State=WorkflowSucceeded;e.workflows[id0]=cloneWorkflow(w);e.mu.Unlock();return nil};step:=w.Steps[w.CurrentStep];e.workflows[id0]=cloneWorkflow(w);e.mu.Unlock();if err:=e.executor.Execute(ctx,step);err!=nil{e.mu.Lock();w=e.workflows[id0];w.State=WorkflowPaused;w.LastError=fmt.Sprintf("step %s: %v",step.ID,err);w.Revision++;w.UpdatedAt=time.Now().UTC();e.workflows[id0]=cloneWorkflow(w);e.mu.Unlock();return err};e.mu.Lock();w=e.workflows[id0];w.CurrentStep++;w.LastError="";w.Revision++;w.UpdatedAt=time.Now().UTC();if w.CurrentStep>=len(w.Steps){w.State=WorkflowSucceeded};e.workflows[id0]=cloneWorkflow(w);done:=w.State==WorkflowSucceeded;e.mu.Unlock();if done{return nil}}}
func(e *Engine)Pause(id string)error{if e==nil{return errors.New("workflow engine is required")};e.mu.Lock();defer e.mu.Unlock();w,ok:=e.workflows[id];if !ok{return ErrWorkflowNotFound};if w.State==WorkflowSucceeded||w.State==WorkflowCancelled{return ErrWorkflowNotRunnable};w.State=WorkflowPaused;w.Revision++;w.UpdatedAt=time.Now().UTC();e.workflows[id]=cloneWorkflow(w);return nil}
func(e *Engine)Get(id string)(Workflow,bool){if e==nil{return Workflow{},false};e.mu.RLock();w,ok:=e.workflows[id];e.mu.RUnlock();if !ok{return Workflow{},false};return cloneWorkflow(w),true}
func cloneWorkflow(w Workflow)Workflow{out:=w;out.Steps=append([]WorkflowStep(nil),w.Steps...);for i:=range out.Steps{out.Steps[i].Input=cloneMap(w.Steps[i].Input)};return out}
func cloneMap(in map[string]any)map[string]any{if in==nil{return nil};out:=make(map[string]any,len(in));for k,v:=range in{out[k]=v};return out}
